---
components:
  schemas:
info:
  description: >+
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - TrafficFlowObserved
            type: string
      responses:
        "200":
          content:
            "application/ld+json":
              examples:
                keyvalues:
                  summary: "Key-Values Pairs"
                  value:
                normalized:
                  summary: "Normalized NGSI-LD"
                  value:
          description: OK
      tags:
        - ngsi-ld
tags:
  description: "NGSI-LD Linked-data Format"
  name: ngsi-ld
